#server
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
  #servlet:
   # context-path: /
 
#spring
spring:
  datasource:
    url: jdbc:mysql:///jtsys?characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
  aop:   proxy-target-class: false
#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/sys/*.xml
  
#lOG
logging:
  level:
    com.cy: DEBUG

async-thread-pool:
  corePoolSize: 20
  maxPoolSize: 1000
  keepAliveSeconds: 30
  queueCapacity: 200
  
  
  
  